landscapeName: aswf
landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
project: a092M00001Iw5W8QAJ # LF Public Health Fund
landscapeMemberCategory: LFPH Members
landscapefile: landscape.yml
missingcsvfile: missing.csv
